# Generated by Django 4.1.10 on 2023-08-04 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Enter field title', max_length=50)),
                ('description', models.TextField(help_text='Enter description', max_length=500)),
                ('price', models.FloatField(help_text='Enter price', max_length=10)),
                ('image', models.CharField(max_length=500)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
            ],
            options={
                'ordering': ['title', 'price'],
            },
        ),
    ]
